//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinBooKeApp.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmailText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinBooKeApp.Core.EmailText", typeof(EmailText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new email address.
        /// </summary>
        internal static string ChangeEmailButton {
            get {
                return ResourceManager.GetString("ChangeEmailButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change email address.
        /// </summary>
        internal static string ChangeEmailHeader {
            get {
                return ResourceManager.GetString("ChangeEmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have received a request to change your email address. Please click the button to continue with this process..
        /// </summary>
        internal static string ChangeEmailIntroduction {
            get {
                return ResourceManager.GetString("ChangeEmailIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new email address.
        /// </summary>
        internal static string ChangeEmailSubject {
            get {
                return ResourceManager.GetString("ChangeEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new email address.
        /// </summary>
        internal static string ChangeEmailTitle {
            get {
                return ResourceManager.GetString("ChangeEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Security notice:&lt;/strong&gt; If you did not request this step, please ignore this email. Your account is secure and no changes have been made..
        /// </summary>
        internal static string ChangeEmailWarning {
            get {
                return ResourceManager.GetString("ChangeEmailWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,.
        /// </summary>
        internal static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the button above doesn&apos;t work, copy and paste this link into your browser:.
        /// </summary>
        internal static string PasswordResetAlternative {
            get {
                return ResourceManager.GetString("PasswordResetAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string PasswordResetButton {
            get {
                return ResourceManager.GetString("PasswordResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset Request.
        /// </summary>
        internal static string PasswordResetHeader {
            get {
                return ResourceManager.GetString("PasswordResetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We received a request to reset your password. Click the button below to create a new password..
        /// </summary>
        internal static string PasswordResetIntroduction {
            get {
                return ResourceManager.GetString("PasswordResetIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Your Password.
        /// </summary>
        internal static string PasswordResetTitle {
            get {
                return ResourceManager.GetString("PasswordResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Security Note:&lt;/strong&gt; If you didn&apos;t request this password reset, please ignore this email. Your account is safe and no changes have been made..
        /// </summary>
        internal static string PasswordResetWarning {
            get {
                return ResourceManager.GetString("PasswordResetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have questions, contact us at.
        /// </summary>
        internal static string QA {
            get {
                return ResourceManager.GetString("QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best regards,&lt;br&gt;The Support Team.
        /// </summary>
        internal static string Valediction {
            get {
                return ResourceManager.GetString("Valediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify email address.
        /// </summary>
        internal static string VerifyEmailButton {
            get {
                return ResourceManager.GetString("VerifyEmailButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify email address.
        /// </summary>
        internal static string VerifyEmailHeader {
            get {
                return ResourceManager.GetString("VerifyEmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the button to successfully verify your email address.
        /// </summary>
        internal static string VerifyEmailIntroduction {
            get {
                return ResourceManager.GetString("VerifyEmailIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address verification.
        /// </summary>
        internal static string VerifyEmailSubject {
            get {
                return ResourceManager.GetString("VerifyEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify email address.
        /// </summary>
        internal static string VerifyEmailTitle {
            get {
                return ResourceManager.GetString("VerifyEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Security notice:&lt;/strong&gt; If you did not request this step, please ignore this email. Your account is secure and no changes have been made..
        /// </summary>
        internal static string VerifyEmailWarning {
            get {
                return ResourceManager.GetString("VerifyEmailWarning", resourceCulture);
            }
        }
    }
}
